<?php
/**
 * Başlangıç içerikleri: e-spor koçluk hizmetleri ve paketleri (fiyatlar KDV dahildir).
 * Paket satırı: [ad, fiyat, eski fiyat, süre, oturum, kısa açıklama, detaylı açıklama (HTML), özellikler (satır satır), öne çıkan]
 */

return [
    [
        'slug' => 'valorant-koclugu',
        'title' => 'Valorant Koçluğu',
        'icon' => 'crosshair',
        'short_desc' => 'Aim mekaniği, ajan havuzu, utility kullanımı ve takım iletişimiyle Valorant rankınızı kalıcı olarak yükseltin.',
        'description' => "<p>Valorant Koçluğu; nişan almadan pozisyon almaya, ajan seçiminden ekonomi yönetimine kadar oyunun tüm katmanlarını kapsayan kişiye özel bir gelişim programıdır. Süreç, son maçlarınızın <strong>VOD (maç kaydı) analizi</strong> ile başlar; koçunuz hatalarınızı zaman damgalarıyla tek tek işaretler.</p><p>Ardından crosshair yerleşimi, counter-strafe, spray kontrolü ve flick mekaniği için günlük aim rutini hazırlanır. Seçtiğiniz ajanın lineup'ları, harita bazlı savunma/atak setupları ve round bazlı karar verme (rotate, retake, save) üzerine canlı derslerle çalışılır.</p><h3>Kimler için uygundur?</h3><ul><li>Demir–Altın aralığında takılıp kalan ve hızla yükselmek isteyen oyuncular</li><li>Elmas–Yücelik seviyesinde Radyant hedefleyen rekabetçi oyuncular</li><li>Takımında IGL (oyun içi lider) rolünü üstlenmek isteyenler</li><li>Premier ve amatör turnuvalara hazırlanan oyuncular</li></ul><h3>Nasıl çalışıyoruz?</h3><ol><li>Ön görüşme: hedef, rank, ajan havuzu ve donanım değerlendirmesi</li><li>VOD analizi: son 3–5 maçınızın detaylı incelemesi</li><li>Kişisel gelişim planı ve günlük aim rutini</li><li>Canlı dersler, ekran paylaşımlı maç izleme ve haftalık geri bildirim</li></ol>",
        'highlights' => "VOD (maç kaydı) analizi\nKişisel aim rutini\nAjan & harita stratejisi\nRank hedefli gelişim planı",
        'packages' => [
            ['Aim & Temel Paket', 1490, 1790, '2 Hafta', '3 canlı ders (60 dk)', 'Aim mekaniği, crosshair yerleşimi ve temel pozisyon hatalarına odaklı hızlı başlangıç.', "<p>Valorant'ta en hızlı gelişim, doğru temel alışkanlıklarla başlar. Bu pakette ilk derste ayarlarınız (hassasiyet, DPI, crosshair, grafik) ve donanımınız kontrol edilir; son maçınızdan seçilen anlar birlikte izlenir.</p><p>Size özel 20 dakikalık günlük aim rutini (Aim Lab / Range) hazırlanır. İkinci ve üçüncü derslerde counter-strafe, crosshair yerleşimi ve ilk temas (first contact) hataları üzerinde çalışılır.</p>", "Ayar ve donanım kontrolü\n1 VOD analizi (yazılı rapor)\nKişisel günlük aim rutini\n3 adet 60 dk canlı ders\nDiscord üzerinden soru-cevap", 0],
            ['Rank Atlama Paketi', 3990, 4790, '1 Ay', '8 canlı ders + 4 VOD analizi', 'Ajan havuzu, harita setupları ve round kararlarıyla 1 ayda ölçülebilir rank artışı.', "<p>En çok tercih edilen Valorant paketimizdir. Başlangıçta rankınız, KDA/ADR/HS% verileriniz ve ajan havuzunuz kayıt altına alınır; ay sonunda aynı verilerle gelişiminiz raporlanır.</p><p>Haftada iki canlı ders yapılır: biri mekanik (aim, movement, utility lineup), diğeri makro (rotasyon, ekonomi, mid-round karar). Her hafta bir maçınızın VOD analizi zaman damgalı rapor olarak teslim edilir.</p><p>Paket sonunda gelişim raporu ile birlikte bir sonraki ay için kişisel çalışma planı verilir.</p>", "Başlangıç ve bitiş istatistik raporu\n8 adet 60 dk canlı ders\n4 VOD analizi (zaman damgalı)\n2 ajan için lineup kütüphanesi\nHarita bazlı atak/savunma setupları\nHafta içi Discord desteği", 1],
            ['Radyant Pro Paketi', 8990, 10490, '3 Ay', '24 canlı ders + 12 VOD + duo maç', 'Üst rank ve turnuva hedefi olan oyuncular için üç aylık yoğun profesyonel program.', "<p>Elmas ve üzeri oyuncular ya da turnuva hedefi olan rekabetçi oyuncular için tasarlanmış üç aylık yoğun programdır. Program; mekanik, taktik ve mental olmak üzere üç blok halinde periyotlanır.</p><p>Koçunuzla birlikte duo/5'li maçlara girilerek gerçek zamanlı iletişim ve karar koçluğu yapılır. IGL olmak isteyen oyunculara strat kitabı (playbook) hazırlama ve çağrı yapma eğitimi verilir. Turnuva dönemlerinde rakip analizi desteği sağlanır.</p>", "24 adet 60 dk canlı ders\n12 VOD analizi\nAyda 2 duo / 5'li maç koçluğu\nKişisel strat kitabı (playbook)\nIGL ve iletişim eğitimi\nAylık istatistik ve gelişim raporu\nÖncelikli 7/24 Discord iletişimi", 0],
        ],
    ],
    [
        'slug' => 'league-of-legends-koclugu',
        'title' => 'League of Legends Koçluğu',
        'icon' => 'sword',
        'short_desc' => 'Koridor evresi, dalga yönetimi, harita bilinci ve makro kararlarla Sihirdar Vadisi\'nde fark yaratın.',
        'description' => "<p>League of Legends Koçluğu; koridor evresinden geç oyun takım savaşlarına kadar oyunu bir bütün olarak ele alır. Koçunuz rolünüze (Üst, Orman, Orta, Nişancı, Destek) ve şampiyon havuzunuza göre çalışır.</p><p>Dalga yönetimi (freeze, slow push, crash), ormancı takibi, görüş kontrolü, objektif zamanlaması ve takas (trade) kararları maç kayıtlarınız üzerinden incelenir. Hedef; mekanik yeteneğinizi doğru kararlarla birleştirerek her maçta etkinizi artırmaktır.</p><h3>Kimler için uygundur?</h3><ul><li>Demir–Altın arası lige takılan ve LP kaybını durdurmak isteyenler</li><li>Platin–Elmas oyuncular ve Ustalık hedefleyenler</li><li>Rol değiştirmek veya şampiyon havuzunu daraltmak isteyenler</li><li>Amatör lig ve üniversite turnuvalarına hazırlanan takımlar</li></ul>",
        'highlights' => "Rol ve şampiyon havuzu analizi\nDalga & ormancı yönetimi\nMakro ve objektif kontrolü\nReplay üzerinden canlı ders",
        'packages' => [
            ['Koridor Ustası Paketi', 1390, 1690, '2 Hafta', '3 canlı ders (60 dk)', 'Koridor evresi, dalga yönetimi ve takas mantığına odaklı başlangıç paketi.', "<p>Maçların büyük kısmı ilk 14 dakikada şekillenir. Bu pakette rolünüze göre koridor evresi temelleri çalışılır: son vuruş, dalga kontrolü, takas pencereleri ve ormancı tehlikesine göre konumlanma.</p><p>Bir maç kaydınız birlikte izlenir; size en çok LP kaybettiren üç alışkanlık belirlenip haftalık çalışma listesine dönüştürülür.</p>", "Rol ve şampiyon havuzu değerlendirmesi\n1 replay analizi\nKoridor evresi çalışma rehberi\n3 adet 60 dk canlı ders\nDiscord soru-cevap", 0],
            ['Lig Atlama Paketi', 3790, 4490, '1 Ay', '8 canlı ders + 4 replay analizi', 'Makro, görüş kontrolü ve objektif zamanlamasıyla 1 ayda istikrarlı LP kazanımı.', "<p>Sadece mekanik değil, karar verme becerinizi geliştiren bir aylık programdır. Her hafta bir canlı ders koridor/mikro, bir canlı ders makro (rotasyon, görüş, Ejder–Vadi Uşağı–Baron zamanlamaları) üzerine yapılır.</p><p>Replay analizleri yazılı rapor olarak teslim edilir. Ay sonunda lig, LP, CS/dk, görüş skoru ve KDA verilerinizle gelişim raporu hazırlanır.</p>", "8 adet 60 dk canlı ders\n4 replay analizi (yazılı rapor)\nŞampiyon havuzu optimizasyonu\nRün & eşya dizilimi rehberi\nAy sonu gelişim raporu\nHafta içi Discord desteği", 1],
            ['Challenger Yol Haritası', 8490, 9990, '3 Ay', '24 canlı ders + 12 replay + duo maç', 'Üst ligler ve turnuva için üç aylık profesyonel gelişim ve takım koçluğu desteği.', "<p>Elmas ve üzeri oyuncular ve takım oyununa geçmek isteyenler için üç aylık profesyonel programdır. Draft (seçim-yasaklama) stratejisi, meta okuma, takım kompozisyonu ve iletişim üzerine derinlemesine çalışılır.</p><p>Koçunuzla duo kuyruğa girilerek canlı karar koçluğu yapılır. Turnuva öncesi rakip takımların maçları analiz edilerek draft planı hazırlanır.</p>", "24 adet 60 dk canlı ders\n12 replay analizi\nAyda 2 duo maç koçluğu\nDraft & meta stratejisi eğitimi\nTurnuva rakip analizi\nAylık gelişim raporu\nÖncelikli 7/24 iletişim", 0],
        ],
    ],
    [
        'slug' => 'cs2-koclugu',
        'title' => 'CS2 Koçluğu',
        'icon' => 'target',
        'short_desc' => 'Spray kontrolü, utility (smoke, flash, molotof) kullanımı, pozisyon ve ekonomi yönetimiyle Counter-Strike 2\'de seviye atlayın.',
        'description' => "<p>CS2 Koçluğu; Premier ve FACEIT seviyenizi yükseltmek ya da takımınızı turnuvaya hazırlamak için hazırlanan kapsamlı bir programdır. Demo (maç kaydı) incelemesiyle başlar; ölümlerinizin nedenleri, utility verimliliğiniz ve pozisyon tercihleri analiz edilir.</p><p>Spray paternleri, counter-strafe, crosshair yerleşimi ve peek teknikleri (jiggle, wide, shoulder) çalışılırken; harita bazlı smoke/flash/molotof setleri ve CT–T rolleri üzerine strateji kurulur. Ekonomi yönetimi (eco, force, full buy) ve takım iletişimi programın ayrılmaz parçasıdır.</p><h3>Kimler için uygundur?</h3><ul><li>Premier puanını ve FACEIT seviyesini artırmak isteyen oyuncular</li><li>Entry, AWP, destek, lurker veya IGL rolünde uzmanlaşmak isteyenler</li><li>Amatör takımlar ve turnuva hazırlığındaki 5'li kadrolar</li></ul>",
        'highlights' => "Demo analizi\nSpray & peek teknikleri\nHarita bazlı utility setleri\nEkonomi ve rol yönetimi",
        'packages' => [
            ['Mekanik Temel Paket', 1490, 1790, '2 Hafta', '3 canlı ders (60 dk)', 'Spray kontrolü, counter-strafe ve crosshair yerleşimiyle sağlam bir mekanik temel.', "<p>Ayarlarınız, config dosyanız ve donanımınız kontrol edilerek başlanır. Bir demonuz birlikte izlenir ve en sık yapılan mekanik hatalar belirlenir.</p><p>Size özel antrenman haritaları ve günlük ısınma rutini (aim botz, prefire, deathmatch) hazırlanır. Derslerde spray paternleri ve peek teknikleri birebir çalışılır.</p>", "Config ve ayar optimizasyonu\n1 demo analizi\nGünlük ısınma rutini\n3 adet 60 dk canlı ders\nDiscord soru-cevap", 0],
            ['Premier Yükseliş Paketi', 3990, 4690, '1 Ay', '8 canlı ders + 4 demo analizi', 'Utility setleri, pozisyon ve ekonomi kararlarıyla 1 ayda ölçülebilir puan artışı.', "<p>Haftada iki canlı ders yapılır: biri mekanik ve utility, diğeri taktik (pozisyon, rotasyon, ekonomi). Aktif harita havuzunuzdan seçilen 3 harita için smoke/flash/molotof setleri öğretilir.</p><p>Her hafta bir demo analizi zaman damgalı rapor olarak teslim edilir. Ay sonunda Premier puanı, ADR, HS% ve utility hasarı verileriyle gelişim raporu hazırlanır.</p>", "8 adet 60 dk canlı ders\n4 demo analizi (zaman damgalı)\n3 harita için utility kütüphanesi\nRol bazlı pozisyon rehberi\nAy sonu gelişim raporu\nHafta içi Discord desteği", 1],
            ['FACEIT Pro Paketi', 8990, 10490, '3 Ay', '24 canlı ders + 12 demo + takım antrenmanı', 'Üst seviye oyuncular ve takımlar için üç aylık profesyonel taktik ve turnuva programı.', "<p>FACEIT 8+ seviyesindeki oyuncular ve turnuvaya hazırlanan takımlar için üç aylık programdır. Takım strat kitabı (default, execute, anti-eco, retake setleri) birlikte hazırlanır.</p><p>Ayda iki kez takımınızın antrenman maçına (scrim) koç olarak katılınır, devre arası ve maç sonu değerlendirmesi yapılır. Turnuva öncesi rakip demo analizi sunulur.</p>", "24 adet 60 dk canlı ders\n12 demo analizi\nAyda 2 scrim koçluğu\nTakım strat kitabı hazırlığı\nRakip demo analizi\nAylık gelişim raporu\nÖncelikli 7/24 iletişim", 0],
        ],
    ],
    [
        'slug' => 'pubg-mobile-koclugu',
        'title' => 'PUBG Mobile Koçluğu',
        'icon' => 'mobile',
        'short_desc' => 'Parmak düzeni, sprey kontrolü, rotasyon ve son daire stratejileriyle mobil e-sporda zirveye oynayın.',
        'description' => "<p>PUBG Mobile Koçluğu; mobil e-spora özel olarak tasarlanmış bir programdır. Cihazınız, grafik ayarlarınız, parmak düzeniniz (2–6 parmak) ve hassasiyet ayarlarınız ilk derste optimize edilir.</p><p>Sprey kontrolü, jiroskop kullanımı, peek ve hareket teknikleri çalışılırken; iniş noktası seçimi, rotasyon planı, araç kullanımı ve son daire stratejileri maç kayıtlarınız üzerinden geliştirilir. Squad oyuncuları için rol dağılımı ve iletişim protokolü oluşturulur.</p><h3>Kimler için uygundur?</h3><ul><li>Fatih ve Fatih üstü (Conqueror) hedefleyen oyuncular</li><li>Squad olarak turnuva ve liglere hazırlanan takımlar</li><li>Jiroskop kullanımına geçmek isteyen oyuncular</li></ul>",
        'highlights' => "Cihaz & parmak düzeni optimizasyonu\nSprey ve jiroskop çalışması\nRotasyon & son daire stratejisi\nSquad rol dağılımı",
        'packages' => [
            ['Mobil Başlangıç Paketi', 1190, 1490, '2 Hafta', '3 canlı ders (45 dk)', 'Ayar, parmak düzeni ve sprey kontrolüyle hızlı ve doğru bir başlangıç.', "<p>Cihazınıza uygun grafik/FPS ayarları, hassasiyet kodu ve parmak düzeni birlikte oluşturulur. Eğitim alanında size özel günlük sprey ve tepki rutini hazırlanır.</p><p>Bir maç kaydınız incelenerek en kritik üç hata belirlenir ve derslerde bunlar üzerine çalışılır.</p>", "Cihaz ve ayar optimizasyonu\nKişisel hassasiyet kodu\n1 maç kaydı analizi\n3 adet 45 dk canlı ders\nDiscord soru-cevap", 0],
            ['Fatih Hedef Paketi', 3290, 3890, '1 Ay', '8 canlı ders + 4 maç analizi', 'Rotasyon, daire okuma ve çatışma kararlarıyla 1 ayda rank hedefinize yaklaşın.', "<p>Haftada iki canlı ders yapılır: mekanik (sprey, jiroskop, hareket) ve taktik (iniş, rotasyon, daire okuma, son daire konumlanması). Erangel, Miramar ve Sanhok için rotasyon haritaları hazırlanır.</p><p>Her hafta bir maçınız analiz edilir. Ay sonunda rank, K/D, ortalama hasar ve ilk 10 oranınızla gelişim raporu verilir.</p>", "8 adet 45 dk canlı ders\n4 maç kaydı analizi\n3 harita için rotasyon planı\nJiroskop geçiş programı\nAy sonu gelişim raporu\nHafta içi Discord desteği", 1],
            ['Squad Turnuva Paketi', 7490, 8990, '2 Ay', '4 kişilik kadro · 16 takım dersi', '4 kişilik kadrolar için rol dağılımı, iletişim ve turnuva stratejisi programı.', "<p>Squad olarak turnuvalara hazırlanan takımlar için iki aylık programdır. Her oyuncunun rolü (IGL, fragger, destek, keskin nişancı) belirlenir; iletişim protokolü ve çağrı dili oluşturulur.</p><p>Takım antrenman maçlarına (scrim) koç olarak katılınır, maç sonu değerlendirme yapılır. Turnuva formatına göre puan stratejisi ve iniş planı hazırlanır.</p>", "4 oyuncu için tek paket\n16 adet takım dersi (60 dk)\nRol dağılımı ve iletişim protokolü\nAyda 4 scrim koçluğu\nTurnuva puan stratejisi\nTakım gelişim raporu\nÖncelikli 7/24 iletişim", 0],
        ],
    ],
    [
        'slug' => 'ea-sports-fc-koclugu',
        'title' => 'EA SPORTS FC Koçluğu',
        'icon' => 'gamepad',
        'short_desc' => 'Taktik diziliş, özel talimatlar, savunma ve skill hareketleriyle Ultimate Team ve Division Rivals\'ta daha çok kazanın.',
        'description' => "<p>EA SPORTS FC Koçluğu; futbol oyunlarında rekabetçi seviyede oynamak isteyen oyuncular için hazırlanmıştır. Diziliş ve özel taktik ayarlarınız, oyuncu talimatlarınız ve kadro kurulumunuz birlikte optimize edilir.</p><p>Manuel savunma, jockey, kesici/tackle zamanlaması, hücum kurgusu, skill hareketleri ve bitiricilik çalışılır. Maçlarınızın kayıtları izlenerek gol yediğiniz pozisyonlar ve kaçırdığınız fırsatlar analiz edilir; FUT Champions ve Division Rivals için oyun planı hazırlanır.</p><h3>Kimler için uygundur?</h3><ul><li>Division Rivals'ta küme atlamak isteyen oyuncular</li><li>FUT Champions'a katılan ve rütbe hedefleyenler</li><li>Konsol veya PC'de turnuvalara hazırlanan oyuncular</li></ul>",
        'highlights' => "Diziliş & özel taktik\nManuel savunma çalışması\nSkill ve bitiricilik\nFUT Champions oyun planı",
        'packages' => [
            ['Taktik Başlangıç Paketi', 1190, 1390, '2 Hafta', '3 canlı ders (60 dk)', 'Diziliş, özel taktik ve savunma temelleriyle daha az gol yiyin.', "<p>İlk derste kontrolcü ayarlarınız, kamera ayarı ve kadronuz incelenir. Oyun stilinize uygun diziliş ve özel taktikler birlikte oluşturulur.</p><p>Diğer derslerde manuel savunma ve jockey zamanlaması üzerine çalışılır; bir maç kaydınız analiz edilir.</p>", "Kontrolcü ve kamera ayarları\nKişisel diziliş & özel taktik\n1 maç analizi\n3 adet 60 dk canlı ders\nDiscord soru-cevap", 0],
            ['Division Yükseliş Paketi', 2990, 3590, '1 Ay', '8 canlı ders + 4 maç analizi', 'Savunma, hücum kurgusu ve skill çalışmasıyla Division Rivals\'ta küme atlayın.', "<p>Haftada iki canlı ders yapılır: savunma blokları ve hücum kurguları. Meta skill hareketleri ve bitiricilik teknikleri (timed finesse, low driven) ayrı modüllerde çalışılır.</p><p>Her hafta bir maç analizi teslim edilir. Ay sonunda kazanma oranı, yenilen/atılan gol ve top hakimiyeti verileriyle gelişim raporu hazırlanır.</p>", "8 adet 60 dk canlı ders\n4 maç analizi\nSkill hareketleri çalışma programı\nRakibe göre oyun planı rehberi\nAy sonu gelişim raporu\nHafta içi Discord desteği", 1],
            ['FUT Champions Elit Paketi', 6490, 7690, '2 Ay', '16 canlı ders + hafta sonu canlı destek', 'FUT Champions ve turnuvalar için iki aylık yoğun program ve hafta sonu canlı koçluk.', "<p>Yüksek rütbe hedefleyen oyuncular için iki aylık programdır. Her FUT Champions hafta sonunda maç aralarında canlı değerlendirme yapılır ve rakibe göre taktik değişikliği önerilir.</p><p>Mental hazırlık, tilt yönetimi ve maç arası rutin bu pakete dahildir.</p>", "16 adet 60 dk canlı ders\nHafta sonu canlı maç desteği\nRakip analizi ve oyun planı\nTilt yönetimi ve mental rutin\nİki aylık gelişim raporu\nÖncelikli 7/24 iletişim", 0],
        ],
    ],
    [
        'slug' => 'takim-ve-turnuva-koclugu',
        'title' => 'Takım & Turnuva Koçluğu',
        'icon' => 'trophy',
        'short_desc' => 'E-spor takımları, okul ve kurumsal kadrolar için strateji, iletişim, scrim yönetimi ve turnuva hazırlığı.',
        'description' => "<p>Takım & Turnuva Koçluğu; bireysel yeteneği takım başarısına dönüştürmek isteyen kadrolar içindir. Valorant, League of Legends, CS2, PUBG Mobile ve diğer takım oyunlarında hizmet verilir.</p><p>Program; rol dağılımı, iletişim protokolü (call dili), strateji kitabı (playbook), scrim planlaması ve maç sonu analiz kültürünün oluşturulmasını kapsar. Turnuva öncesinde rakip analizi, draft/harita veto stratejisi ve maç günü rutini hazırlanır.</p><h3>Kimler için uygundur?</h3><ul><li>Amatör ve yarı profesyonel e-spor takımları</li><li>Üniversite ve lise e-spor kulüpleri</li><li>Kurumsal e-spor turnuvalarına katılan şirket takımları</li><li>Kendi takımını kurmak isteyen kulüp ve organizasyonlar</li></ul>",
        'highlights' => "Rol dağılımı ve iletişim\nStrateji kitabı (playbook)\nScrim yönetimi\nRakip analizi & veto stratejisi",
        'packages' => [
            ['Takım Kurulum Paketi', 4990, 5990, '1 Ay', '5 kişilik kadro · 6 takım dersi', 'Rol dağılımı, iletişim dili ve antrenman takvimiyle takımınızı doğru kurun.', "<p>Yeni kurulan veya yeniden yapılanan takımlar için başlangıç paketidir. Her oyuncuyla birebir ön görüşme yapılarak roller belirlenir; takım içi iletişim dili ve antrenman takvimi oluşturulur.</p><p>Takım derslerinde temel stratejiler ve iletişim alıştırmaları yapılır. Ay sonunda takımın güçlü ve gelişime açık yönlerini içeren rapor teslim edilir.</p>", "5 oyuncu + 1 yedek için tek paket\nOyuncularla birebir ön görüşme\n6 adet 90 dk takım dersi\nİletişim protokolü & call dili\nHaftalık antrenman takvimi\nTakım değerlendirme raporu", 0],
            ['Sezon Hazırlık Paketi', 11900, 13900, '2 Ay', '16 takım dersi + 8 scrim koçluğu', 'Lig ve turnuva sezonuna hazırlanan takımlar için iki aylık kapsamlı program.', "<p>Lig ve turnuva sezonuna hazırlanan takımlar için en çok tercih edilen paketimizdir. Takımın strateji kitabı (playbook) birlikte hazırlanır, her hafta scrim'lere koç olarak katılınır.</p><p>Maç sonu VOD analizleri takım toplantısıyla birlikte değerlendirilir. Sezon başlamadan önce rakip analizleri ve harita/draft veto planı teslim edilir.</p>", "16 adet 90 dk takım dersi\n8 scrim koçluğu\nTakım strateji kitabı\nHaftalık takım VOD analizi\nRakip analizleri\nVeto / draft stratejisi\nÖncelikli 7/24 iletişim", 1],
            ['Turnuva Günü Koçluğu', 3490, null, 'Tek turnuva', 'Hazırlık dersi + maç günü canlı koçluk', 'Turnuva öncesi hazırlık ve maç günü boyunca canlı koç desteği.', "<p>Tek bir turnuva için hazırlanan pakettir. Turnuvadan önce bir hazırlık dersi yapılır, rakip takımların maçları analiz edilir ve oyun planı oluşturulur.</p><p>Maç günü koçunuz takımınızla birlikte olur (online), maç araları ve devre aralarında taktik düzeltmeler yapar. Turnuva sonrası değerlendirme raporu teslim edilir.</p>", "1 adet 120 dk hazırlık dersi\nRakip analizi (2 takıma kadar)\nMaç günü canlı koçluk\nVeto / draft planı\nTurnuva sonrası değerlendirme raporu", 0],
        ],
    ],
    [
        'slug' => 'e-spor-mental-performans-koclugu',
        'title' => 'E-Spor Mental Performans Koçluğu',
        'icon' => 'brain',
        'short_desc' => 'Tilt yönetimi, odak, maç stresi ve sağlıklı oyun rutiniyle performansınızı zihinsel olarak güçlendirin.',
        'description' => "<p>E-spor yalnızca mekanik beceri değildir; uzun maç serileri, kayıp serileri ve turnuva baskısı performansı doğrudan etkiler. Mental Performans Koçluğu; tilt yönetimi, odak, özgüven ve baskı altında karar verme becerilerinizi geliştirmeye odaklanır.</p><p>Bunun yanında uyku düzeni, ekran süresi, ergonomi, mola ve ısınma rutini gibi sağlıklı oyun alışkanlıkları üzerine kişisel bir plan hazırlanır. Program tüm oyunlardaki oyuncular ve takımlar için uygundur.</p><p><em>Not: Bu hizmet bir performans koçluğu hizmetidir; psikolojik tanı veya tedavi içermez. Gerekli görülmesi halinde danışana bir uzmana başvurması önerilir.</em></p><h3>Kimler için uygundur?</h3><ul><li>Kayıp serilerinde motivasyonunu ve oyununu kaybeden oyuncular</li><li>Turnuvada antrenmandaki performansını gösteremeyenler</li><li>Takım içi iletişimde gerginlik yaşayan kadrolar</li><li>Oyun–okul/iş dengesini kurmak isteyen oyuncular</li></ul>",
        'highlights' => "Tilt yönetimi\nOdak ve nefes teknikleri\nMaç günü rutini\nSağlıklı oyun alışkanlıkları",
        'packages' => [
            ['Odak Başlangıç Paketi', 1290, 1490, '2 Hafta', '3 birebir görüşme (50 dk)', 'Tilt tetikleyicilerinizi tanıyın, maç arası toparlanma rutini oluşturun.', "<p>İlk görüşmede oyun alışkanlıklarınız, tilt tetikleyicileriniz ve hedefleriniz konuşulur. Size özel maç öncesi ve maç arası rutin (nefes, odak, kısa mola) hazırlanır.</p><p>İki hafta boyunca kısa bir performans günlüğü tutmanız istenir; son görüşmede günlük birlikte değerlendirilir.</p>", "Ön değerlendirme görüşmesi\nKişisel maç öncesi rutin\nTilt yönetimi teknikleri\n3 adet 50 dk birebir görüşme\nPerformans günlüğü şablonu", 0],
            ['Zihinsel Güç Paketi', 3490, 3990, '1 Ay', '6 birebir görüşme + haftalık takip', 'Özgüven, baskı altında karar ve sağlıklı oyun düzeni için bir aylık program.', "<p>Haftada bir birebir görüşme ve hafta içi kısa yazılı takip ile ilerleyen bir aylık programdır. Hedef belirleme, baskı altında karar verme, olumsuz iç konuşmayı yönetme ve özgüven çalışmaları yapılır.</p><p>Uyku, beslenme, ekran süresi ve ergonomi alışkanlıklarınız için kişisel bir plan oluşturulur.</p>", "6 adet 50 dk birebir görüşme\nHaftalık yazılı takip\nHedef belirleme çalışması\nSağlıklı oyun rutini planı\nTurnuva günü hazırlık protokolü\nAy sonu değerlendirme raporu", 1],
            ['Takım Mental Paketi', 6990, 7990, '1 Ay', '5 kişilik kadro · 4 takım + 5 birebir görüşme', 'Takım içi iletişim, güven ve baskı yönetimi için takım bazlı mental program.', "<p>Takımlar için hazırlanmış bir aylık programdır. Takım atölyelerinde iletişim, geri bildirim kültürü, kayıp sonrası toparlanma ve ortak hedef belirleme çalışılır.</p><p>Her oyuncuyla bir birebir görüşme yapılır. Program sonunda takım dinamiği raporu ve sürdürülebilir alışkanlık önerileri teslim edilir.</p>", "4 adet 90 dk takım atölyesi\nHer oyuncuyla 1 birebir görüşme\nİletişim ve geri bildirim protokolü\nKayıp sonrası toparlanma rutini\nTakım dinamiği raporu", 0],
        ],
    ],
    [
        'slug' => 'yayinci-ve-icerik-uretici-koclugu',
        'title' => 'Yayıncı & İçerik Üretici Koçluğu',
        'icon' => 'stream',
        'short_desc' => 'Twitch, Kick ve YouTube\'da yayın kurulumu, içerik planı, topluluk yönetimi ve kişisel marka ile büyüyün.',
        'description' => "<p>E-spor kariyerinin önemli ayaklarından biri de yayıncılık ve içerik üretimidir. Bu koçluk; oyun yayıncısı veya e-spor içerik üreticisi olmak isteyenlere teknik kurulumdan kişisel markaya kadar uçtan uca destek verir.</p><p>OBS ayarları, sahne ve overlay tasarımı, ses-görüntü kalitesi, yayın takvimi, kısa video (Shorts/Reels/TikTok) stratejisi, topluluk ve Discord yönetimi, sponsorluk dosyası hazırlığı programın başlıklarıdır.</p><h3>Kimler için uygundur?</h3><ul><li>Yayına yeni başlayacak veya yayınlarını büyütemeyen oyuncular</li><li>Profesyonel oyuncu olup kişisel markasını güçlendirmek isteyenler</li><li>E-spor takımları için içerik üretmek isteyen ekipler</li></ul>",
        'highlights' => "OBS & yayın kurulumu\nİçerik ve yayın takvimi\nKısa video stratejisi\nSponsorluk dosyası",
        'packages' => [
            ['Yayın Kurulum Paketi', 1590, 1890, '2 Hafta', '3 canlı ders (60 dk)', 'OBS, ses-görüntü ayarları, sahneler ve ilk yayın planı ile doğru başlangıç.', "<p>Bilgisayarınıza ve internet bağlantınıza göre OBS (bit hızı, kodlayıcı, çözünürlük) ayarları birlikte yapılır. Sahne yapısı, uyarılar (alert) ve sohbet botu kurulur.</p><p>Platform seçimi ve ilk ay için yayın takvimi oluşturulur.</p>", "OBS ve yayın ayarları\nSahne ve uyarı kurulumu\nSohbet botu kurulumu\n3 adet 60 dk canlı ders\nİlk ay yayın takvimi", 0],
            ['Büyüme Paketi', 3990, 4590, '1 Ay', '6 canlı ders + 4 yayın analizi', 'İçerik planı, kısa video stratejisi ve topluluk yönetimiyle izleyici sayınızı artırın.', "<p>Yayınlarınızdan seçilen bölümler izlenerek sunum, tempo ve izleyici etkileşimi analiz edilir. Kısa video (Shorts/Reels/TikTok) için kesit ve başlık stratejisi oluşturulur.</p><p>Discord sunucusu ve topluluk kuralları yapılandırılır. Ay sonunda takipçi, ortalama izleyici ve izlenme süresi verileriyle gelişim raporu hazırlanır.</p>", "6 adet 60 dk canlı ders\n4 yayın analizi\nKısa video stratejisi\nDiscord topluluk kurulumu\nAylık içerik takvimi\nAy sonu gelişim raporu", 1],
            ['Marka & Sponsorluk Paketi', 7990, 9490, '2 Ay', '10 canlı ders + medya kiti', 'Kişisel marka, medya kiti ve sponsorluk görüşmelerine hazırlık ile profesyonelleşin.', "<p>Belirli bir izleyici kitlesine ulaşmış yayıncılar ve profesyonel oyuncular için iki aylık programdır. Kişisel marka konumlandırması, görsel kimlik rehberi ve medya kiti (media kit) hazırlanır.</p><p>Sponsorluk teklif dosyası birlikte oluşturulur, marka görüşmeleri için sunum ve fiyatlandırma çalışılır.</p>", "10 adet 60 dk canlı ders\nKişisel marka konumlandırması\nMedya kiti (PDF) hazırlığı\nSponsorluk teklif dosyası\nMarka görüşmesi provası\nÖncelikli 7/24 iletişim", 0],
        ],
    ],
];
