<?php
/** Veritabanı tabloları (MySQL ve SQLite uyumlu) - GS Sportif Ürünler mağaza */

function schema_sql(string $driver): array
{
    $mysql = $driver === 'mysql';
    $pk = $mysql ? 'INT UNSIGNED AUTO_INCREMENT PRIMARY KEY' : 'INTEGER PRIMARY KEY AUTOINCREMENT';
    $int = $mysql ? 'INT UNSIGNED' : 'INTEGER';
    $txt = $mysql ? 'MEDIUMTEXT' : 'TEXT';
    $tail = $mysql ? ' ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci' : '';

    return [
        "CREATE TABLE IF NOT EXISTS users (
            id $pk,
            name VARCHAR(120) NOT NULL,
            email VARCHAR(190) NOT NULL UNIQUE,
            phone VARCHAR(30) NULL,
            password_hash VARCHAR(255) NOT NULL,
            role VARCHAR(20) NOT NULL DEFAULT 'member',
            status VARCHAR(10) NOT NULL DEFAULT 'active',
            created_by $int NULL,
            last_login_at DATETIME NULL,
            reset_token VARCHAR(64) NULL,
            reset_expires DATETIME NULL,
            created_at DATETIME NOT NULL
        )$tail",
        "CREATE TABLE IF NOT EXISTS categories (
            id $pk,
            slug VARCHAR(160) NOT NULL UNIQUE,
            name VARCHAR(160) NOT NULL,
            description VARCHAR(500) NULL,
            color VARCHAR(20) NOT NULL DEFAULT '#C8102E',
            sort_order INT NOT NULL DEFAULT 0,
            is_active TINYINT NOT NULL DEFAULT 1,
            created_at DATETIME NOT NULL,
            updated_at DATETIME NOT NULL
        )$tail",
        "CREATE TABLE IF NOT EXISTS products (
            id $pk,
            category_id $int NOT NULL,
            slug VARCHAR(190) NOT NULL UNIQUE,
            name VARCHAR(190) NOT NULL,
            short_desc VARCHAR(400) NOT NULL,
            description $txt NOT NULL,
            features TEXT NULL,
            gender VARCHAR(10) NOT NULL DEFAULT 'unisex',
            price DECIMAL(12,2) NOT NULL,
            old_price DECIMAL(12,2) NULL,
            images TEXT NULL,
            art VARCHAR(20) NOT NULL DEFAULT 'tshirt',
            art_color VARCHAR(20) NOT NULL DEFAULT '#C8102E',
            personalizable TINYINT NOT NULL DEFAULT 0,
            personalization_price DECIMAL(12,2) NOT NULL DEFAULT 0,
            is_featured TINYINT NOT NULL DEFAULT 0,
            is_active TINYINT NOT NULL DEFAULT 1,
            sort_order INT NOT NULL DEFAULT 0,
            created_at DATETIME NOT NULL,
            updated_at DATETIME NOT NULL
        )$tail",
        "CREATE TABLE IF NOT EXISTS product_variants (
            id $pk,
            product_id $int NOT NULL,
            size VARCHAR(20) NOT NULL,
            color VARCHAR(60) NOT NULL,
            color_hex VARCHAR(20) NOT NULL DEFAULT '#2B2F33',
            sku VARCHAR(60) NULL,
            stock INT NOT NULL DEFAULT 0,
            sort_order INT NOT NULL DEFAULT 0
        )$tail",
        "CREATE TABLE IF NOT EXISTS coupons (
            id $pk,
            code VARCHAR(40) NOT NULL UNIQUE,
            type VARCHAR(10) NOT NULL DEFAULT 'percent',
            value DECIMAL(12,2) NOT NULL,
            min_total DECIMAL(12,2) NOT NULL DEFAULT 0,
            max_uses INT NOT NULL DEFAULT 0,
            used_count INT NOT NULL DEFAULT 0,
            starts_at DATETIME NULL,
            expires_at DATETIME NULL,
            is_active TINYINT NOT NULL DEFAULT 1,
            created_at DATETIME NOT NULL
        )$tail",
        "CREATE TABLE IF NOT EXISTS orders (
            id $pk,
            order_no VARCHAR(40) NOT NULL UNIQUE,
            user_id $int NULL,
            subtotal DECIMAL(12,2) NOT NULL,
            discount DECIMAL(12,2) NOT NULL DEFAULT 0,
            coupon_code VARCHAR(40) NULL,
            shipping_fee DECIMAL(12,2) NOT NULL DEFAULT 0,
            amount DECIMAL(12,2) NOT NULL,
            item_count INT NOT NULL DEFAULT 0,
            customer_name VARCHAR(120) NOT NULL,
            customer_email VARCHAR(190) NOT NULL,
            customer_phone VARCHAR(30) NOT NULL,
            ship_name VARCHAR(120) NOT NULL,
            ship_phone VARCHAR(30) NOT NULL,
            ship_address VARCHAR(500) NOT NULL,
            ship_district VARCHAR(80) NOT NULL,
            ship_city VARCHAR(60) NOT NULL,
            customer_address VARCHAR(500) NOT NULL,
            customer_city VARCHAR(60) NULL,
            identity_no VARCHAR(20) NULL,
            invoice_type VARCHAR(12) NOT NULL DEFAULT 'bireysel',
            company_name VARCHAR(200) NULL,
            tax_office VARCHAR(100) NULL,
            tax_number VARCHAR(20) NULL,
            customer_note TEXT NULL,
            status VARCHAR(20) NOT NULL DEFAULT 'pending',
            stock_reduced TINYINT NOT NULL DEFAULT 0,
            cargo_company VARCHAR(60) NULL,
            tracking_no VARCHAR(80) NULL,
            shipped_at DATETIME NULL,
            delivered_at DATETIME NULL,
            payment_method VARCHAR(30) NULL,
            payment_ref VARCHAR(100) NULL,
            payment_message VARCHAR(500) NULL,
            payment_raw TEXT NULL,
            assigned_to $int NULL,
            contract_accepted_at DATETIME NULL,
            ip VARCHAR(45) NULL,
            paid_at DATETIME NULL,
            created_at DATETIME NOT NULL,
            updated_at DATETIME NOT NULL
        )$tail",
        "CREATE TABLE IF NOT EXISTS order_items (
            id $pk,
            order_id $int NOT NULL,
            product_id $int NULL,
            variant_id $int NULL,
            product_name VARCHAR(190) NOT NULL,
            size VARCHAR(20) NOT NULL,
            color VARCHAR(60) NOT NULL,
            print_name VARCHAR(30) NULL,
            print_number VARCHAR(5) NULL,
            unit_price DECIMAL(12,2) NOT NULL,
            qty INT NOT NULL,
            line_total DECIMAL(12,2) NOT NULL
        )$tail",
        "CREATE TABLE IF NOT EXISTS order_notes (
            id $pk,
            order_id $int NOT NULL,
            user_id $int NULL,
            user_name VARCHAR(120) NOT NULL,
            note TEXT NOT NULL,
            created_at DATETIME NOT NULL
        )$tail",
        "CREATE TABLE IF NOT EXISTS team_requests (
            id $pk,
            club_name VARCHAR(160) NOT NULL,
            contact_name VARCHAR(120) NOT NULL,
            email VARCHAR(190) NOT NULL,
            phone VARCHAR(30) NOT NULL,
            city VARCHAR(60) NULL,
            sport VARCHAR(60) NULL,
            quantity INT NOT NULL DEFAULT 0,
            products VARCHAR(500) NULL,
            needed_by DATE NULL,
            message TEXT NULL,
            status VARCHAR(20) NOT NULL DEFAULT 'new',
            quote_amount DECIMAL(12,2) NULL,
            assigned_to $int NULL,
            ip VARCHAR(45) NULL,
            created_at DATETIME NOT NULL,
            updated_at DATETIME NOT NULL
        )$tail",
        "CREATE TABLE IF NOT EXISTS pages (
            id $pk,
            slug VARCHAR(120) NOT NULL UNIQUE,
            title VARCHAR(200) NOT NULL,
            content $txt NOT NULL,
            show_in_footer TINYINT NOT NULL DEFAULT 1,
            sort_order INT NOT NULL DEFAULT 0,
            updated_by $int NULL,
            updated_at DATETIME NOT NULL
        )$tail",
        "CREATE TABLE IF NOT EXISTS messages (
            id $pk,
            name VARCHAR(120) NOT NULL,
            email VARCHAR(190) NOT NULL,
            phone VARCHAR(30) NULL,
            subject VARCHAR(200) NOT NULL,
            message TEXT NOT NULL,
            status VARCHAR(12) NOT NULL DEFAULT 'new',
            assigned_to $int NULL,
            ip VARCHAR(45) NULL,
            created_at DATETIME NOT NULL
        )$tail",
        "CREATE TABLE IF NOT EXISTS activity_log (
            id $pk,
            user_id $int NULL,
            user_name VARCHAR(120) NOT NULL,
            user_role VARCHAR(20) NOT NULL,
            action VARCHAR(120) NOT NULL,
            entity VARCHAR(40) NULL,
            entity_id $int NULL,
            details TEXT NULL,
            ip VARCHAR(45) NULL,
            created_at DATETIME NOT NULL
        )$tail",
        "CREATE TABLE IF NOT EXISTS settings (
            skey VARCHAR(80) NOT NULL PRIMARY KEY,
            svalue TEXT NULL
        )$tail",
        "CREATE INDEX idx_orders_created ON orders (created_at)",
        "CREATE INDEX idx_orders_status ON orders (status)",
        "CREATE INDEX idx_items_order ON order_items (order_id)",
        "CREATE INDEX idx_variants_product ON product_variants (product_id)",
        "CREATE INDEX idx_products_category ON products (category_id)",
        "CREATE INDEX idx_activity_created ON activity_log (created_at)",
    ];
}
