<?php
/** Başlangıç içerikleri: danışmanlık hizmetleri ve paketleri (fiyatlar KDV dahildir) */

return [
    [
        'slug' => 'sporcu-performans-danismanligi',
        'title' => 'Sporcu Performans Danışmanlığı',
        'icon' => 'performance',
        'short_desc' => 'Bilimsel testler ve kişiye özel antrenman planlamasıyla sporcunun kuvvet, sürat ve dayanıklılık kapasitesini en üst seviyeye taşıyoruz.',
        'description' => "<p>Sporcu Performans Danışmanlığı; branşınıza, yaşınıza, sezon takviminize ve hedeflerinize göre tamamen kişiselleştirilmiş bir gelişim programıdır. Süreç, performans analiz testleriyle başlar ve mevcut durumunuz ölçülebilir verilerle ortaya konur.</p><p>Uzman antrenörlerimiz elde edilen verilere göre periyotlanmış bir antrenman planı hazırlar; kuvvet, patlayıcı güç, sürat, çeviklik, dayanıklılık ve mobilite bileşenlerini dengeli şekilde geliştirir. Program boyunca düzenli kontrol görüşmeleriyle gelişiminiz takip edilir ve plan güncellenir.</p><h3>Kimler için uygundur?</h3><ul><li>Profesyonel ve amatör lisanslı sporcular</li><li>Altyapıdan A takıma geçiş sürecindeki genç oyuncular</li><li>Sezon öncesi hazırlık dönemindeki sporcular</li><li>Performansını veriyle takip etmek isteyen bireysel sporcular</li></ul>",
        'highlights' => "Performans analiz testleri\nPeriyotlanmış antrenman planı\nHaftalık gelişim takibi\nBranşa özel çalışma içerikleri",
        'packages' => [
            ['Başlangıç Paketi', 25000, null, '1 Ay', '4 online görüşme', 'Temel performans değerlendirmesi ve 4 haftalık kişisel antrenman planı.', "<p>Performans yolculuğuna başlamak isteyen sporcular için tasarlanmış giriş paketidir. İlk görüşmede sporcunun geçmişi, sakatlık öyküsü ve hedefleri değerlendirilir; ardından evde veya salonda uygulanabilecek temel testlerle başlangıç verileri toplanır.</p><p>Toplanan verilere göre 4 haftalık, haftada 3-4 antrenman gününden oluşan kişisel plan hazırlanır. Her hafta yapılan online görüşmelerle uygulama kontrol edilir ve gerekli düzeltmeler yapılır.</p>", "Ön değerlendirme görüşmesi (45 dk)\nTemel performans testleri rehberi\n4 haftalık kişisel antrenman planı\nHaftalık online kontrol görüşmesi\nE-posta ile soru-cevap desteği", 0],
            ['Profesyonel Paket', 39900, 44900, '3 Ay', '12 online görüşme', 'Detaylı test bataryası, 12 haftalık periyotlanmış program ve aylık rapor.', "<p>Sezon hedefi olan sporcular için en çok tercih edilen paketimizdir. Kapsamlı test bataryası (sıçrama, sürat, çeviklik, kuvvet ve aerobik kapasite) ile detaylı profil çıkarılır.</p><p>12 haftalık program hazırlık, gelişim ve zirve bloklarına ayrılarak periyotlanır. Her ayın sonunda test tekrarlanır ve gelişim grafiklerle raporlanır. WhatsApp üzerinden hafta içi destek sağlanır.</p>", "Kapsamlı performans test bataryası\n12 haftalık periyotlanmış program\nHaftalık online görüşme (12 adet)\nAylık gelişim raporu ve grafikler\nVideo ile teknik analiz (ayda 2)\nHafta içi WhatsApp desteği", 1],
            ['Elit Paket', 59900, 64900, '6 Ay', '24 görüşme + 2 yüz yüze', 'Sezon boyu tam kapsamlı performans yönetimi ve yüz yüze test günleri.', "<p>Profesyonel sporcular için sezon boyu tam kapsamlı performans yönetimidir. Program, yüz yüze gerçekleştirilen laboratuvar testi günü ile başlar ve sezon takvimine göre mikro/makro döngülere bölünür.</p><p>Maç ve yarışma yoğunluğuna göre yük yönetimi yapılır, toparlanma protokolleri planlanır. Sporcunun kulüp antrenörleriyle koordinasyon sağlanarak bütüncül bir yaklaşım benimsenir.</p>", "2 adet yüz yüze test günü\n6 aylık sezon planlaması\nHaftalık görüşme (24 adet)\nYük ve toparlanma yönetimi\nKulüp antrenörüyle koordinasyon\nÖncelikli 7/24 iletişim\nSezon sonu kapsamlı performans raporu", 0],
        ],
    ],
    [
        'slug' => 'sporcu-beslenmesi-danismanligi',
        'title' => 'Sporcu Beslenmesi Danışmanlığı',
        'icon' => 'nutrition',
        'short_desc' => 'Antrenman yüküne, branşa ve vücut kompozisyonu hedeflerine göre hazırlanan bilimsel temelli beslenme programları.',
        'description' => "<p>Doğru beslenme, antrenmanın karşılığını almanın en kritik adımıdır. Sporcu Beslenmesi Danışmanlığı kapsamında spor diyetisyenlerimiz; antrenman saatleriniz, enerji harcamanız ve hedeflerinize göre kişisel beslenme planı hazırlar.</p><p>Maç/yarışma günü beslenmesi, toparlanma dönemi, kilo sınıfı olan branşlarda sağlıklı kilo yönetimi ve takviye kullanımı konularında bilimsel kanıta dayalı rehberlik sunulur.</p><h3>Neler kazanırsınız?</h3><ul><li>Daha hızlı toparlanma</li><li>Hedefe uygun vücut kompozisyonu</li><li>Antrenman ve maç günlerinde yüksek enerji</li><li>Sakatlık riskinin azaltılması</li></ul>",
        'highlights' => "Vücut kompozisyonu analizi\nKişisel beslenme programı\nMaç günü beslenme protokolü\nTakviye kullanım rehberi",
        'packages' => [
            ['Başlangıç Paketi', 25000, null, '1 Ay', '2 online görüşme', 'Kişisel beslenme programı ve iki kontrol görüşmesi.', "<p>Beslenme düzenini sporcu ihtiyaçlarına göre yeniden kurmak isteyenler için giriş paketidir. İlk görüşmede beslenme alışkanlıkları, antrenman programı ve hedefler değerlendirilir.</p><p>Kişisel beslenme programı ve alışveriş listesi hazırlanır; 2. haftadaki kontrol görüşmesinde program güncellenir.</p>", "Beslenme alışkanlığı değerlendirmesi\nKişisel beslenme programı\nAlışveriş ve öğün hazırlama listesi\n2 online kontrol görüşmesi", 0],
            ['Profesyonel Paket', 39900, 44900, '3 Ay', '6 online görüşme', 'Antrenman günlerine göre değişen periyotlu beslenme ve takviye planı.', "<p>Antrenman, dinlenme ve maç günlerine göre ayrı ayrı planlanan periyotlu beslenme programıdır. Vücut kompozisyonu hedefleri 2 haftalık kontrollerle takip edilir.</p><p>Kanıta dayalı takviye rehberi ile hangi ürünü, ne zaman ve ne miktarda kullanmanız gerektiği netleştirilir.</p>", "Periyotlu beslenme programı\nAntrenman / maç / dinlenme günü menüleri\nTakviye kullanım rehberi\n2 haftada bir kontrol (6 görüşme)\nVücut ölçüm takip tablosu\nMesaj ile destek", 1],
            ['Elit Paket', 59900, 64900, '6 Ay', '12 görüşme', 'Sezon boyu beslenme yönetimi, kamp ve seyahat beslenme planları.', "<p>Profesyonel sporcular için sezon boyu beslenme yönetimidir. Hazırlık kampı, deplasman seyahatleri ve turnuva dönemleri için özel planlar hazırlanır.</p><p>Gerekli durumlarda kan tahlili sonuçları değerlendirilerek sağlık profesyonelleriyle koordinasyon sağlanır.</p>", "6 aylık sezon beslenme planı\nKamp ve seyahat beslenme protokolleri\nTahlil sonuçlarının değerlendirilmesi\n12 kontrol görüşmesi\nÖncelikli mesaj desteği\nAylık ilerleme raporu", 0],
        ],
    ],
    [
        'slug' => 'kulup-yonetimi-danismanligi',
        'title' => 'Kulüp Yönetimi ve Organizasyon Danışmanlığı',
        'icon' => 'club',
        'short_desc' => 'Spor kulüpleri için kurumsal yapılanma, altyapı sistemi, sponsorluk ve sürdürülebilir finansal yönetim danışmanlığı.',
        'description' => "<p>Amatör ve profesyonel spor kulüplerinin kurumsal, finansal ve sportif açıdan sürdürülebilir bir yapıya kavuşması için uçtan uca danışmanlık sunuyoruz.</p><p>Organizasyon şeması, görev tanımları, altyapı (akademi) sistemi, lisans ve federasyon süreçleri, sponsorluk stratejisi ve bütçe planlaması başlıklarında kulübünüzün mevcut durumu analiz edilir ve uygulanabilir bir yol haritası hazırlanır.</p><h3>Çalışma alanlarımız</h3><ul><li>Kurumsal yapılanma ve görev tanımları</li><li>Altyapı / akademi sistemi kurulumu</li><li>Sponsorluk ve gelir modelleri</li><li>Bütçe ve finansal planlama</li><li>Dijital iletişim ve taraftar ilişkileri</li></ul>",
        'highlights' => "Kurumsal yapı analizi\nAltyapı sistemi kurulumu\nSponsorluk stratejisi\nBütçe ve finans planı",
        'packages' => [
            ['Analiz Paketi', 25000, null, '1 Ay', '4 toplantı', 'Kulübün mevcut durum analizi ve öncelikli aksiyon raporu.', "<p>Kulübünüzün yönetim, finans, sportif yapı ve iletişim alanlarındaki mevcut durumunu analiz ediyoruz. Yönetim kurulu ve teknik ekiple yapılan görüşmeler sonucunda güçlü/zayıf yönler belirlenir.</p><p>Süreç sonunda önceliklendirilmiş aksiyon listesini içeren detaylı analiz raporu teslim edilir.</p>", "Yönetim ve teknik ekip görüşmeleri\nSWOT ve mevcut durum analizi\nFinansal yapı ön incelemesi\nÖnceliklendirilmiş aksiyon raporu\nRapor sunum toplantısı", 0],
            ['Yapılanma Paketi', 34900, 39900, '3 Ay', '12 toplantı', 'Organizasyon şeması, görev tanımları, altyapı sistemi ve sponsorluk dosyası.', "<p>Analiz çalışmasının ardından kulübün kurumsal yapılanmasını birlikte kuruyoruz. Organizasyon şeması ve görev tanımları hazırlanır, altyapı sisteminin yaş grupları bazında çalışma modeli oluşturulur.</p><p>Potansiyel sponsorlara sunulmak üzere profesyonel sponsorluk dosyası ve fiyatlandırma modeli hazırlanır.</p>", "Analiz Paketi'nin tüm içeriği\nOrganizasyon şeması ve görev tanımları\nAltyapı / akademi çalışma modeli\nSponsorluk dosyası ve fiyat modeli\nYıllık bütçe taslağı\n12 haftalık uygulama takibi", 1],
            ['Kurumsal Paket', 69900, 79900, '12 Ay', 'Aylık yerinde ziyaret', 'Bir sezon boyunca yerinde danışmanlık ve yönetim desteği.', "<p>Bir tam sezon boyunca kulübünüzün yanındayız. Aylık yerinde ziyaretler, yönetim kurulu toplantılarına katılım ve süreç takibiyle hazırlanan planların hayata geçirilmesini sağlıyoruz.</p><p>Sponsor görüşmelerine destek, federasyon ve lisans süreçlerinde rehberlik ve dönemsel performans raporlaması pakete dahildir.</p>", "Yapılanma Paketi'nin tüm içeriği\n12 ay boyunca aylık yerinde ziyaret\nYönetim toplantılarına katılım\nSponsor görüşmelerinde destek\nFederasyon ve lisans süreç rehberliği\nÇeyrek dönem performans raporları\nÖncelikli iletişim hattı", 0],
        ],
    ],
    [
        'slug' => 'sporcu-kariyer-danismanligi',
        'title' => 'Sporcu Kariyer ve Menajerlik Danışmanlığı',
        'icon' => 'career',
        'short_desc' => 'Sporcu profili oluşturma, kulüp/transfer süreçleri, sözleşme okuryazarlığı ve kariyer sonrası planlama.',
        'description' => "<p>Sporcunun kariyeri, sahadaki performansı kadar doğru kararlara da bağlıdır. Kariyer ve Menajerlik Danışmanlığı ile sporcuların kariyer hedeflerini netleştiriyor, görünürlüklerini artırıyor ve profesyonel süreçlerde doğru adımlar atmalarına yardımcı oluyoruz.</p><p>Sporcu profil dosyası ve tanıtım videosu hazırlığı, kulüp ve scout ağına tanıtım stratejisi, sözleşme maddelerinin anlaşılması ve kariyer sonrası planlama başlıklarında rehberlik sunuyoruz.</p><p><em>Not: Danışmanlık hizmetlerimiz hukuki temsil içermez; sözleşme imzası öncesi avukat görüşü alınması önerilir.</em></p>",
        'highlights' => "Profesyonel sporcu profili\nTanıtım videosu kurgusu\nKulüp tanıtım stratejisi\nSözleşme okuryazarlığı",
        'packages' => [
            ['Profil Paketi', 25000, null, '2 Hafta', '2 online görüşme', 'Profesyonel sporcu CV\'si ve tanıtım dosyası hazırlığı.', "<p>Kulüplere ve scoutlara sunulabilecek profesyonel sporcu profil dosyası hazırlanır. Sporcunun istatistikleri, fiziksel verileri, kariyer geçmişi ve başarıları düzenli ve etkileyici bir formatta sunulur.</p>", "Kariyer hedefi görüşmesi\nProfesyonel sporcu CV'si (TR/EN)\nTanıtım dosyası (PDF)\nSosyal medya profil önerileri", 0],
            ['Kariyer Paketi', 39900, 44900, '3 Ay', '6 görüşme', 'Tanıtım videosu, kulüp hedef listesi ve kariyer yol haritası.', "<p>Profil hazırlığının ötesinde, sporcunun seviyesine uygun kulüp hedef listesi oluşturulur ve tanıtım stratejisi planlanır. Maç görüntülerinden profesyonel tanıtım videosu kurgulanır.</p><p>Sözleşme görüşmeleri öncesi dikkat edilmesi gereken maddeler hakkında bilgilendirme yapılır.</p>", "Profil Paketi'nin tüm içeriği\nProfesyonel tanıtım videosu kurgusu\nHedef kulüp listesi ve strateji\nSözleşme okuryazarlığı eğitimi\n3 aylık kariyer yol haritası\n6 online görüşme", 1],
            ['Elit Kariyer Paketi', 59900, 64900, '12 Ay', 'Aylık görüşme + etkinlik', 'Bir yıl boyunca kariyer yönetimi, marka ve medya danışmanlığı.', "<p>Bir yıl boyunca sporcunun kariyer yönetimine eşlik ediyoruz. Kişisel marka ve medya iletişimi, sponsorluk fırsatları, finansal okuryazarlık ve kariyer sonrası planlama başlıklarında düzenli danışmanlık sunulur.</p>", "Kariyer Paketi'nin tüm içeriği\n12 ay kariyer yönetimi desteği\nKişisel marka ve medya danışmanlığı\nSponsorluk fırsatı değerlendirmesi\nFinansal okuryazarlık oturumları\nKariyer sonrası planlama", 0],
        ],
    ],
    [
        'slug' => 'spor-tesisi-proje-danismanligi',
        'title' => 'Spor Tesisi Proje Danışmanlığı',
        'icon' => 'facility',
        'short_desc' => 'Saha, salon, fitness merkezi ve spor kompleksleri için fizibilite, konsept tasarım ve işletme modeli danışmanlığı.',
        'description' => "<p>GS Projeler'in uzmanlık alanlarından biri olan tesis projelendirmesinde; yatırımcılara, belediyelere, okullara ve kulüplere fikir aşamasından açılışa kadar rehberlik ediyoruz.</p><p>Pazar ve konum analizi, fizibilite ve yatırım geri dönüş hesabı, federasyon standartlarına uygun alan planlaması, zemin/aydınlatma/ekipman seçimi ve işletme modeli kurgusu hizmet kapsamımızdadır.</p><h3>Proje tipleri</h3><ul><li>Futbol, halı saha ve çok amaçlı sahalar</li><li>Kapalı spor salonları</li><li>Fitness ve performans merkezleri</li><li>Yüzme havuzları ve spor kompleksleri</li></ul>",
        'highlights' => "Fizibilite ve ROI analizi\nFederasyon standartlarına uygunluk\nEkipman ve zemin seçimi\nİşletme modeli",
        'packages' => [
            ['Ön Fizibilite Paketi', 25000, null, '3 Hafta', '3 toplantı', 'Konum, pazar ve yatırım geri dönüşü ön analizi.', "<p>Yatırım kararı öncesinde projenin uygulanabilirliğini ortaya koyan ön fizibilite çalışmasıdır. Konum ve rakip analizi, hedef kitle ve talep tahmini, yaklaşık yatırım bütçesi ve geri dönüş süresi hesaplanır.</p>", "Konum ve rakip analizi\nTalep ve hedef kitle tahmini\nYaklaşık yatırım bütçesi\nGeri dönüş (ROI) hesabı\nÖn fizibilite raporu", 0],
            ['Konsept Proje Paketi', 49900, 54900, '2 Ay', '8 toplantı', 'Detaylı fizibilite, alan planlaması ve ekipman listesi.', "<p>Detaylı fizibilite çalışmasına ek olarak tesisin fonksiyonel alan planlaması yapılır. Federasyon ve ilgili yönetmelik standartlarına uygun ölçüler, zemin, aydınlatma ve ekipman seçimleri belirlenir; tedarikçi karşılaştırmaları hazırlanır.</p>", "Ön Fizibilite Paketi'nin tüm içeriği\nDetaylı finansal model\nFonksiyonel alan planlaması\nZemin, aydınlatma ve ekipman listesi\nTedarikçi karşılaştırma tablosu\nMimari ekip için ihtiyaç programı", 1],
            ['Anahtar Teslim Danışmanlık', 99900, 109900, '6 Ay', 'Proje boyu takip', 'Fikirden açılışa tüm sürecin yönetimi ve işletme kurgusu.', "<p>Projenin fikir aşamasından açılışına kadar tüm süreçte yatırımcının yanında yer alıyoruz. Tedarikçi seçimi ve ihale süreçlerine destek, uygulama kontrolü, işletme modeli, fiyatlandırma, personel yapısı ve açılış pazarlama planı pakete dahildir.</p>", "Konsept Proje Paketi'nin tüm içeriği\nTedarikçi ve ihale süreç desteği\nUygulama sürecinde saha kontrolleri\nİşletme modeli ve fiyatlandırma\nPersonel yapısı ve görev tanımları\nAçılış pazarlama planı", 0],
        ],
    ],
    [
        'slug' => 'sporcu-psikolojisi-mental-kocluk',
        'title' => 'Sporcu Psikolojisi ve Mental Koçluk',
        'icon' => 'mental',
        'short_desc' => 'Baskı altında performans, odaklanma, motivasyon ve özgüven için sporcuya özel mental antrenman programları.',
        'description' => "<p>Zirvedeki sporcuları ayıran çoğu zaman fiziksel değil zihinsel farktır. Mental koçluk programlarımızla sporcuların baskı altında karar verme, odaklanma, kaygı yönetimi ve özgüven becerilerini sistematik biçimde geliştiriyoruz.</p><p>Hedef belirleme, imgeleme (görselleştirme), nefes ve odak teknikleri, maç öncesi rutin oluşturma ve hata sonrası toparlanma gibi uygulamalı teknikler kişiye özel olarak planlanır.</p><p><em>Not: Mental koçluk hizmeti klinik psikolojik tedavi yerine geçmez; gerekli durumlarda uzman sağlık profesyoneline yönlendirme yapılır.</em></p>",
        'highlights' => "Baskı altında performans\nOdak ve konsantrasyon\nMaç öncesi rutinler\nHedef belirleme",
        'packages' => [
            ['Başlangıç Paketi', 25000, null, '1 Ay', '4 seans', 'Mental beceri değerlendirmesi ve temel teknik eğitimi.', "<p>Mental performans becerilerinin değerlendirildiği ve temel tekniklerin öğretildiği giriş paketidir. 4 seans boyunca nefes, odak ve maç öncesi rutin teknikleri uygulamalı olarak çalışılır.</p>", "Mental beceri değerlendirme ölçeği\n4 bireysel online seans (50 dk)\nNefes ve odak teknikleri\nKişisel maç öncesi rutin", 0],
            ['Gelişim Paketi', 39900, 44900, '3 Ay', '12 seans', 'Kapsamlı mental antrenman programı ve performans günlüğü.', "<p>Üç ay boyunca haftalık seanslarla yürütülen kapsamlı mental antrenman programıdır. İmgeleme, öz-konuşma, kaygı yönetimi ve hata sonrası toparlanma becerileri sistematik şekilde geliştirilir. Sporcu, performans günlüğü ile gelişimini takip eder.</p>", "12 bireysel online seans\nİmgeleme ve öz-konuşma çalışmaları\nKaygı ve baskı yönetimi\nPerformans günlüğü şablonu\nMaç sonrası değerlendirme görüşmeleri\nMesaj ile destek", 1],
            ['Takım Paketi', 59900, 64900, '2 Ay', '6 grup + 6 bireysel', 'Takımlar için iletişim, liderlik ve takım uyumu çalışmaları.', "<p>Takımlar ve teknik ekipler için tasarlanmış mental performans programıdır. Grup atölyeleriyle takım içi iletişim, liderlik ve ortak hedef bilinci geliştirilir; kaptan ve kilit oyuncularla bireysel seanslar yapılır.</p>", "6 grup atölyesi (en fazla 25 kişi)\n6 bireysel seans (kaptan / kilit oyuncular)\nTakım uyumu değerlendirmesi\nTeknik ekip için rehber dokümanı\nProgram sonu raporu", 0],
        ],
    ],
    [
        'slug' => 'sakatlik-onleme-rehabilitasyon',
        'title' => 'Sakatlık Önleme ve Sahaya Dönüş Danışmanlığı',
        'icon' => 'rehab',
        'short_desc' => 'Hareket analizi ile sakatlık risklerini belirleyen, sakatlık sonrası güvenli sahaya dönüş sürecini planlayan danışmanlık.',
        'description' => "<p>Sakatlıklar sporcunun hem sezonunu hem kariyerini etkileyebilir. Bu danışmanlık hizmetinde fonksiyonel hareket analizi ile risk faktörleri belirlenir ve kişiye özel önleyici egzersiz programı hazırlanır.</p><p>Sakatlık geçirmiş sporcular için ise hekim ve fizyoterapist tedavisini tamamlayıcı nitelikte, kademeli ve kriter bazlı sahaya dönüş programı planlanır.</p><p><em>Not: Bu hizmet tıbbi tanı ve tedavi yerine geçmez; hekim onayı ile yürütülür.</em></p>",
        'highlights' => "Fonksiyonel hareket analizi\nÖnleyici egzersiz programı\nKriter bazlı sahaya dönüş\nHekim ile koordinasyon",
        'packages' => [
            ['Risk Analizi Paketi', 25000, null, '2 Hafta', '2 görüşme', 'Hareket analizi ve kişisel sakatlık önleme programı.', "<p>Video tabanlı fonksiyonel hareket analizi ile mobilite, stabilite ve asimetri değerlendirilir. Tespit edilen risklere yönelik, antrenman öncesi ısınmaya entegre edilebilecek önleyici egzersiz programı hazırlanır.</p>", "Video tabanlı hareket analizi\nRisk değerlendirme raporu\nKişisel önleyici egzersiz programı\n2 online görüşme", 0],
            ['Sahaya Dönüş Paketi', 39900, 44900, '6 Hafta', '6 görüşme', 'Sakatlık sonrası kademeli ve kriter bazlı sahaya dönüş planı.', "<p>Hekim tarafından antrenmana dönüş izni verilen sporcular için kademeli sahaya dönüş programıdır. Her aşamanın geçiş kriterleri belirlenir; kuvvet, sürat ve branşa özel hareketler güvenli şekilde yeniden kazandırılır.</p>", "Mevcut durum değerlendirmesi\n6 haftalık kriter bazlı program\nHaftalık ilerleme görüşmesi\nAşama geçiş testleri\nHekim/fizyoterapist ile koordinasyon", 1],
            ['Sezon Koruma Paketi', 59900, 64900, '6 Ay', '12 görüşme', 'Sezon boyu yük izleme ve sakatlık önleme programı.', "<p>Sezon boyunca antrenman ve maç yükü izlenir, yorgunluk ve risk göstergelerine göre program güncellenir. Periyodik hareket analizleri ile gelişim takip edilir.</p>", "Sezon başı ve ortası hareket analizi\nYük izleme tablosu\nDönemsel önleyici program güncellemesi\n12 online görüşme\nÖncelikli mesaj desteği", 0],
        ],
    ],
];
